services:
  - type: web
    name: mpfback-twitterclone
    env: python
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 3"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mpfback-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12.0

databases:
  - name: mpfback-db
    plan: free